name: mocha_point
description: A Flutter coffee subscription app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  intl: ^0.19.0
  confetti: ^0.7.0

  # Authentication packages - Latest versions
  http: ^1.2.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  crypto: ^3.0.3

  # Test the Google Sign-In package
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/shops/
    - assets/images/redeem.png
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
    - family: Mocha
      fonts:
        - asset: assets/fonts/mocha.otf
    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/ClashDisplay-Regular.otf
        - asset: assets/fonts/ClashDisplay-Bold.otf
          weight: 700
        - asset: assets/fonts/ClashDisplay-SemiBold.otf
          weight: 600
        - asset: assets/fonts/ClashDisplay-Medium.otf
          weight: 500

flutter_launcher_name:
  name: "Mocha Point"

flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "#4C2915"

flutter_native_splash:
  color: "#4C2915"
  image: assets/icon/mocha_icon_black.png
  android: true
  ios: true
  web: false

  android_12:
    color: "#FAF5F2"
    image: assets/icon/mocha_icon_black.png
    icon_background_color: "#4C2915"